services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: turnero_user
      POSTGRES_PASSWORD: turnero_pw
      POSTGRES_DB: turnero_db
